(function(g){var window=this;'use strict';var Hl9=function(E){E.publish("autonavvisibility")},TGT=function(E,b){E.w2("onAutonavCoundownStarted",b)},MT7=function(E){var b,Z,A;
return E==null?void 0:(b=E.playerOverlays)==null?void 0:(Z=b.playerOverlayRenderer)==null?void 0:(A=Z.autoplay)==null?void 0:A.playerOverlayAutoplayRenderer},K2=function(E,b,Z){g.VH(E.element,"ytp-suggestion-set",!!b.videoId);
var A=b.playlistId;Z=b.Ox(Z?Z:"mqdefault.jpg");var K=null,k=null;b instanceof g.D0&&(b.lengthText?(K=b.lengthText||null,k=b.yk||null):b.lengthSeconds&&(K=g.ea(b.lengthSeconds),k=g.ea(b.lengthSeconds,!0)));var X=!!A;A=X&&g.eh(A).type==="RD";var Q=b instanceof g.D0?b.isLivePlayback:null,l=b instanceof g.D0?b.isUpcoming:null,V=b.author,w=b.shortViewCount,p=b.publishedTimeText,W=[],L=[];V&&W.push(V);w&&(W.push(w),L.push(w));p&&L.push(p);Z={title:b.title,author:V,author_and_views:W.join(" \u2022 "),aria_label:b.ariaLabel||
g.JI("Watch $TITLE",{TITLE:b.title}),duration:K,timestamp:k,url:b.SI(),is_live:Q,is_upcoming:l,is_list:X,is_mix:A,background:Z?"background-image: url("+Z+")":"",views_and_publish_time:L.join(" \u2022 "),autoplayAlternativeHeader:b.J0};b instanceof g.Gm&&(Z.playlist_length=b.playlistLength);E.update(Z)},kV=function(E){var b=E.C(),Z=b.V;
g.O.call(this,{W:"a",U:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:Z?b.L:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},Y:[{W:"div",Km:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},Y:[{W:"div",X:{"aria-label":"{{timestamp}}"},Km:["ytp-autonav-timestamp"],kf:"{{duration}}"},{W:"div",Km:["ytp-autonav-live-stamp"],kf:"Live"},{W:"div",
Km:["ytp-autonav-upcoming-stamp"],kf:"Upcoming"},{W:"div",U:"ytp-autonav-list-overlay",Y:[{W:"div",U:"ytp-autonav-mix-text",kf:"Mix"},{W:"div",U:"ytp-autonav-mix-icon"}]}]},{W:"div",Km:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],kf:"{{title}}"},{W:"div",Km:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],kf:"{{author}}"},{W:"div",Km:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],kf:"{{views_and_publish_time}}"}]});this.J=E;this.suggestion=
null;this.D=Z;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},X$=function(E,b){b=b===void 0?!1:b;
g.O.call(this,{W:"div",U:"ytp-autonav-endscreen-countdown-overlay"});var Z=this;this.N=b;this.cancelCommand=this.G=void 0;this.j=0;this.container=new g.O({W:"div",U:"ytp-autonav-endscreen-countdown-container"});g.R(this,this.container);this.container.bD(this.element);b=E.C();var A=b.V;this.J=E;this.suggestion=null;this.onVideoDataChange("newdata",g.U(this.J.getVideoData()));this.B(E,"videodatachange",this.onVideoDataChange);this.D=new g.O({W:"div",U:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},Y:[{W:"div",U:"ytp-autonav-endscreen-upnext-header"},{W:"div",U:"ytp-autonav-endscreen-upnext-alternative-header",kf:"{{autoplayAlternativeHeader}}"},{W:"a",U:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:A?b.L:""},Y:[{W:"div",U:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},Y:[{W:"div",X:{"aria-label":"{{timestamp}}"},Km:["ytp-autonav-timestamp"],
kf:"{{duration}}"},{W:"div",Km:["ytp-autonav-live-stamp"],kf:"Live"},{W:"div",Km:["ytp-autonav-upcoming-stamp"],kf:"Upcoming"}]},{W:"div",U:"ytp-autonav-endscreen-video-info",Y:[{W:"div",U:"ytp-autonav-endscreen-premium-badge"},{W:"div",U:"ytp-autonav-endscreen-upnext-title",kf:"{{title}}"},{W:"div",U:"ytp-autonav-endscreen-upnext-author",kf:"{{author}}"},{W:"div",U:"ytp-autonav-view-and-date",kf:"{{views_and_publish_time}}"},{W:"div",U:"ytp-autonav-author-and-view",kf:"{{author_and_views}}"}]}]}]});
g.R(this,this.D);this.D.bD(this.container.element);A||this.B(this.D.Wx("ytp-autonav-endscreen-link-container"),"click",this.U3);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.D.Wx("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.O({W:"div",U:"ytp-autonav-overlay"});g.R(this,this.overlay);this.overlay.bD(this.container.element);this.T=new g.O({W:"div",U:"ytp-autonav-endscreen-button-container"});g.R(this,this.T);this.T.bD(this.container.element);
this.cancelButton=new g.O({W:"button",Km:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.Z("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel autoplay"},kf:"Cancel"});g.R(this,this.cancelButton);this.cancelButton.bD(this.T.element);this.cancelButton.listen("click",this.lY,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.O({W:"a",Km:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.Z("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},kf:"Play Now"});g.R(this,this.playButton);this.playButton.bD(this.T.element);this.playButton.listen("click",this.U3,this);this.J.createServerVe(this.playButton.element,this.playButton,!0);(b=this.J.getVideoData())&&qe8(this,b);this.V=new g.S6(function(){$19(Z)},500);
g.R(this,this.V);this.NN();this.B(E,"autonavvisibility",this.NN);this.J.Z("web_autonav_color_transition")&&(this.B(E,"autonavchange",this.T4),this.B(E,"onAutonavCoundownStarted",this.BwO))},f2=function(E){var b=E.J.us(!0,E.J.isFullscreen());
g.VH(E.container.element,"ytp-autonav-endscreen-small-mode",E.dV(b));g.VH(E.container.element,"ytp-autonav-endscreen-is-premium",!!E.suggestion&&!!E.suggestion.m4x);g.VH(E.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!E.J.bO());g.VH(E.J.getRootNode(),"countdown-running",E.fV());g.VH(E.container.element,"ytp-player-content",E.J.bO());g.Y6(E.overlay.element,{width:b.width+"px"});if(!E.fV()){E.J.bO()?zzB(E,Math.round(FcR(E)/1E3)):zzB(E);b=!!E.suggestion&&!!E.suggestion.J0;var Z=E.J.bO()||
!b;g.VH(E.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!Z&&b);g.VH(E.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",Z&&!b);E.T.aX(E.J.bO());g.VH(E.element,"ytp-enable-w2w-color-transitions",U18(E))}},$19=function(E){var b=FcR(E),Z=Math,A=Z.min;
var K=E.j?Date.now()-E.j:0;Z=A.call(Z,K,b);zzB(E,Math.ceil((b-Z)/1E3));b-Z<=500&&E.fV()?E.select(!0):E.fV()&&E.V.start()},FcR=function(E){if(E.J.isFullscreen()){var b;
E=(b=E.J.getVideoData())==null?void 0:b.ac;return E===-1||E===void 0?8E3:E}return E.J.HY()>=0?E.J.HY():g.iJ(E.J.C().experiments,"autoplay_time")||1E4},qe8=function(E,b){b=b.getWatchNextResponse();
var Z,A;b=(Z=MT7(b))==null?void 0:(A=Z.nextButton)==null?void 0:A.buttonRenderer;E.G=b==null?void 0:b.navigationEndpoint;Z=b==null?void 0:b.trackingParams;E.playButton&&Z&&E.J.setTrackingParams(E.playButton.element,Z)},U18=function(E){var b;
return!((b=E.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},zzB=function(E,b){b=b===void 0?-1:b;
E=E.D.Wx("ytp-autonav-endscreen-upnext-header");g.AJ(E);if(b>=0){b=String(b);var Z="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],A="Up next in $SECONDS".indexOf(Z);if(A>=0){E.appendChild(g.bB("Up next in $SECONDS".slice(0,A)));var K=g.E5("span");g.KG(K,"ytp-autonav-endscreen-upnext-header-countdown-number");g.fa(K,b);E.appendChild(K);E.appendChild(g.bB("Up next in $SECONDS".slice(A+Z.length)));return}}g.fa(E,"Up next")},Q3=function(E,b){g.O.call(this,{W:"div",
Km:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=E},lT=function(E){g.O.call(this,{W:"div",
Km:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},Y:[{W:"div",U:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{W:"span",U:"ytp-upnext-top",Y:[{W:"span",U:"ytp-upnext-header",kf:"Up Next"},{W:"span",U:"ytp-upnext-title",kf:"{{title}}"},{W:"span",U:"ytp-upnext-author",kf:"{{author}}"}]},{W:"a",U:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},Y:[{W:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
Y:[{W:"circle",U:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{W:"circle",U:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{W:"path",U:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{W:"span",U:"ytp-upnext-bottom",Y:[{W:"span",U:"ytp-upnext-cancel"},{W:"span",U:"ytp-upnext-paused",
kf:"Autoplay is paused"}]}]});this.api=E;this.cancelButton=null;this.G=this.Wx("ytp-svg-autoplay-ring");this.j=this.notification=this.D=this.suggestion=null;this.V=new g.S6(this.LF,5E3,this);this.T=0;var b=this.Wx("ytp-upnext-cancel");this.cancelButton=new g.O({W:"button",Km:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel autoplay"},kf:"Cancel"});g.R(this,this.cancelButton);this.cancelButton.listen("click",this.z4,this);this.cancelButton.bD(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.R(this,this.V);this.api.createClientVe(this.element,this,18788);b=this.Wx("ytp-upnext-autoplay-icon");this.B(b,"click",this.kV);this.api.createClientVe(b,this,115130);this.BF();this.B(E,"autonavvisibility",this.BF);this.B(E,"mdxnowautoplaying",this.iw_);this.B(E,"mdxautoplaycanceled",this.JK9);g.VH(this.element,"ytp-upnext-mobile",this.api.C().T)},g5T=function(E,b){if(b)return b;
if(E.api.isFullscreen()){var Z;E=(Z=E.api.getVideoData())==null?void 0:Z.ac;return E===-1||E===void 0?8E3:E}return E.api.HY()>=0?E.api.HY():g.iJ(E.api.C().experiments,"autoplay_time")||1E4},sGB=function(E,b){b=g5T(E,b);
var Z=Math,A=Z.min;var K=(0,g.v)()-E.T;Z=A.call(Z,K,b);b=b===0?1:Math.min(Z/b,1);E.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&E.fV()&&E.api.getPresentingPlayerType()!==3?E.select(!0):E.fV()&&E.D.start()},V3=function(E){Q3.call(this,E,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.O({W:"div",U:"ytp-suggestion-panel",Y:[{W:"div",Km:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],kf:"More videos"}]});this.S=new g.O({W:"div",U:"ytp-suggestions-container"});this.videos=[];this.j=null;this.G=this.N=!1;this.T=new X$(this.player);g.R(this,this.T);this.T.bD(this.element);E.getVideoData().gC?this.D=this.T:(this.D=new lT(E),g.gP(this.player,this.D.element,4),g.R(this,this.D));this.overlay=new g.O({W:"div",
U:"ytp-autonav-overlay-cancelled-state"});g.R(this,this.overlay);this.overlay.bD(this.element);this.V=new g.R8(this);g.R(this,this.V);g.R(this,this.table);this.table.bD(this.element);this.table.show();g.R(this,this.S);this.S.bD(this.table.element);this.hide()},w2=function(E){var b=E.bO();
b!==E.G&&(E.G=b,Hl9(E.player),E.G?(E.T!==E.D&&E.T.hide(),E.table.hide()):(E.T!==E.D&&E.T.show(),E.table.show()))},p2=function(E,b){g.O.call(this,{W:"button",
Km:["ytp-watch-on-youtube-button","ytp-button"],kf:"{{content}}"});this.J=E;this.buttonType=this.buttonType=b;this.Lo();this.buttonType===2&&g.XV(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Lo);this.aX(!0)},Wa=function(E,b){Q3.call(this,E,"embeds-lite-endscreen");
this.J=E;this.D=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new p2(E,2);g.R(this,this.watchButton);this.watchButton.bD(this.element);this.hide()},L2=function(E){var b=E.C(),Z=g.go||g.T$?{style:"will-change: opacity"}:void 0,A=b.V,K=["ytp-modern-videowall-still"];
b.T&&K.push("ytp-videowall-show-text");g.O.call(this,{W:"a",Km:K,X:{href:"{{url}}",target:A?b.L:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},Y:[{W:"div",U:"ytp-modern-videowall-still-image",X:{style:"{{background}}"},Y:[{W:"span",U:"ytp-modern-videowall-still-info-duration",kf:"{{duration}}"}]},{W:"span",U:"ytp-modern-videowall-still-info",X:{"aria-hidden":"true"},Y:[{W:"span",U:"ytp-modern-videowall-still-info-bg",Y:[{W:"span",
U:"ytp-modern-videowall-still-info-content",X:Z,Y:[{W:"span",U:"ytp-modern-videowall-still-info-title",kf:"{{title}}"},{W:"span",U:"ytp-modern-videowall-still-info-author",kf:"{{author_and_views}}"},{W:"span",U:"ytp-modern-videowall-still-info-live",kf:"Live"}]}]}]},{W:"span",Km:["ytp-modern-videowall-still-listlabel-regular","ytp-modern-videowall-still-listlabel"],X:{"aria-hidden":"true"},Y:[{W:"span",U:"ytp-modern-videowall-still-listlabel-icon"},"Playlist",{W:"span",U:"ytp-modern-videowall-still-listlabel-length",
Y:[" (",{W:"span",kf:"{{playlist_length}}"},")"]}]},{W:"span",Km:["ytp-modern-videowall-still-listlabel-mix","ytp-modern-videowall-still-listlabel"],X:{"aria-hidden":"true"},Y:[{W:"span",U:"ytp-modern-videowall-still-listlabel-mix-icon"},"Mix",{W:"span",U:"ytp-modern-videowall-still-listlabel-length",kf:" (50+)"}]}]});this.suggestion=null;this.T=A;this.api=E;this.D=new g.R8(this);g.R(this,this.D);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.D.B(E,"videodatachange",
this.onVideoDataChange);E.createServerVe(this.element,this);this.onVideoDataChange()},d1F=function(E){Q3.call(this,E,"videowall-endscreen");
var b=this;this.J=E;this.stills=[];this.j=this.videoData=null;this.V=this.N=!1;this.S=null;g.XV(this.element,"modern-videowall-endscreen");this.T=new g.R8(this);g.R(this,this.T);this.G=new g.S6(function(){g.XV(b.element,"ytp-show-tiles")},0);
g.R(this,this.G);this.table=new g.wr({W:"div",U:"ytp-modern-endscreen-content"});g.R(this,this.table);this.table.bD(this.element);E.getVideoData().gC?this.D=new X$(E,!0):this.D=new lT(E);g.R(this,this.D);g.gP(this.player,this.D.element,4);E.createClientVe(this.element,this,158789);this.hide()},Ba=function(E){return g.sd(E.player)&&E.OP()&&!E.j},iT=function(E){var b=E.bO();
b!==E.N&&(E.N=b,Hl9(E.player))},YeB=function(E){Q3.call(this,E,"subscribecard-endscreen");
this.D=new g.O({W:"div",U:"ytp-subscribe-card",Y:[{W:"img",U:"ytp-author-image",X:{src:"{{profilePicture}}"}},{W:"div",U:"ytp-subscribe-card-right",Y:[{W:"div",U:"ytp-author-name",kf:"{{author}}"},{W:"div",U:"html5-subscribe-button-container"}]}]});g.R(this,this.D);this.D.bD(this.element);var b=E.getVideoData();this.subscribeButton=new g.uC("Subscribe",null,"Unsubscribe",null,!0,!1,b.TU,b.subscribed,"trailer-endscreen",null,E,!1);g.R(this,this.subscribeButton);this.subscribeButton.bD(this.D.Wx("html5-subscribe-button-container"));
this.B(E,"videodatachange",this.uD);this.uD();this.hide()},Ix=function(E){var b=E.C(),Z=g.go||g.T$?{style:"will-change: opacity"}:void 0,A=b.V,K=["ytp-videowall-still"];
b.T&&K.push("ytp-videowall-show-text");g.O.call(this,{W:"a",Km:K,X:{href:"{{url}}",target:A?b.L:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},Y:[{W:"div",U:"ytp-videowall-still-image",X:{style:"{{background}}"}},{W:"span",U:"ytp-videowall-still-info",X:{"aria-hidden":"true"},Y:[{W:"span",U:"ytp-videowall-still-info-bg",Y:[{W:"span",U:"ytp-videowall-still-info-content",X:Z,Y:[{W:"span",U:"ytp-videowall-still-info-title",kf:"{{title}}"},
{W:"span",U:"ytp-videowall-still-info-author",kf:"{{author_and_views}}"},{W:"span",U:"ytp-videowall-still-info-live",kf:"Live"},{W:"span",U:"ytp-videowall-still-info-duration",kf:"{{duration}}"}]}]}]},{W:"span",Km:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},Y:[{W:"span",U:"ytp-videowall-still-listlabel-icon"},"Playlist",{W:"span",U:"ytp-videowall-still-listlabel-length",Y:[" (",{W:"span",kf:"{{playlist_length}}"},")"]}]},{W:"span",Km:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},Y:[{W:"span",U:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{W:"span",U:"ytp-videowall-still-listlabel-length",kf:" (50+)"}]}]});this.suggestion=null;this.T=A;this.api=E;this.D=new g.R8(this);g.R(this,this.D);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.D.B(E,"videodatachange",this.onVideoDataChange);E.createServerVe(this.element,this);this.onVideoDataChange()},Nt=function(E){Q3.call(this,E,"videowall-endscreen");
var b=this;this.J=E;this.j=0;this.stills=[];this.V=this.videoData=null;this.G=this.S=!1;this.L=null;this.T=new g.R8(this);g.R(this,this.T);this.N=new g.S6(function(){g.XV(b.element,"ytp-show-tiles")},0);
g.R(this,this.N);var Z=new g.O({W:"button",Km:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},Y:[g.rr()]});g.R(this,Z);Z.bD(this.element);Z.listen("click",this.iY,this);this.table=new g.wr({W:"div",U:"ytp-endscreen-content"});g.R(this,this.table);this.table.bD(this.element);Z=new g.O({W:"button",Km:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},Y:[g.aY()]});g.R(this,Z);Z.bD(this.element);Z.listen("click",this.Wk,this);E.getVideoData().gC?this.D=new X$(E,!0):this.D=
new lT(E);g.R(this,this.D);g.gP(this.player,this.D.element,4);E.createClientVe(this.element,this,158789);this.hide()},J4=function(E){return g.sd(E.player)&&E.OP()&&!E.V},r2=function(E){var b=E.bO();
b!==E.S&&(E.S=b,Hl9(E.player))},ax=function(E){Q3.call(this,E,"watch-again-on-youtube-endscreen");
this.watchButton=new p2(E,1);g.R(this,this.watchButton);this.watchButton.bD(this.element);g.drZ(E)&&(this.D=new g.ub(E),g.R(this,this.D),this.T=new g.O({W:"div",Km:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},Y:[this.D]}),g.R(this,this.T),this.D.bD(this.T.element),this.T.bD(this.element));E.createClientVe(this.element,this,156914);this.hide()},ylB=function(E){g.BM.call(this,E);
var b=this;this.endScreen=null;this.T=this.D=this.j=this.V=!1;this.listeners=new g.R8(this);g.R(this,this.listeners);var Z=E.C(),A=E.getVideoData();A=A&&A.limitedPlaybackDurationInSeconds!==0;g.VU(g.C_(Z))&&A&&!g.$e(E)?(this.T=!0,this.endScreen=new Wa(E,g.Ik(E))):E.isEmbedsShortsMode()?this.endScreen=new ax(E):C97(E)?(this.V=!0,Rzs(this),this.D?this.endScreen=new V3(E):Z.Z("delhi_modern_endscreen")?this.endScreen=new d1F(E):this.endScreen=new Nt(E)):Z.IS?this.endScreen=new YeB(E):this.endScreen=new Q3(E);
g.R(this,this.endScreen);g.gP(E,this.endScreen.element,4);o5s(this);this.listeners.B(E,"videodatachange",this.onVideoDataChange,this);this.listeners.B(E,g.Q2("endscreen"),function(K){b.onCueRangeEnter(K)});
this.listeners.B(E,g.lF("endscreen"),function(K){b.onCueRangeExit(K)})},Rzs=function(E){var b=E.player.getVideoData();
if(!b||E.D===b.cZ&&E.j===b.gC)return!1;E.D=b.cZ;E.j=b.gC;return!0},C97=function(E){E=E.C();
return E.Kw&&!E.IS&&!E.disableOrganicUi},o5s=function(E){E.player.r6("endscreen");
var b=E.player.getVideoData();b=new g.Xz(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var Z=new g.Xz(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});E.player.m1([b,Z])};
g.HQ.prototype.HY=g.XL(14,function(){return this.app.HY()});
g.LT.prototype.HY=g.XL(13,function(){return this.getVideoData().Wb});
g.xe.prototype.q7=g.XL(12,function(E){this.fg().q7(E)});
g.lv.prototype.q7=g.XL(11,function(E){this.D!==E&&(this.D=E,this.uD())});
g.Hr.prototype.q7=g.XL(10,function(E){this.overflowButton&&this.overflowButton.q7(E)});
g.xe.prototype.gG=g.XL(9,function(E){this.fg().gG(E)});
g.Bf.prototype.gG=g.XL(8,function(E){this.T!==E&&(this.T=E,this.uD())});
g.Hr.prototype.gG=g.XL(7,function(E){this.shareButton&&this.shareButton.gG(E)});
g.xe.prototype.TD=g.XL(6,function(E){this.fg().TD(E)});
g.oz.prototype.TD=g.XL(5,function(E){this.oE!==E&&(this.oE=E,this.Fz())});
g.xe.prototype.Ic=g.XL(4,function(E){this.fg().Ic(E)});
g.Hr.prototype.Ic=g.XL(3,function(E){this.XF!==E&&(this.XF=E,this.WJ())});g.N(kV,g.O);kV.prototype.select=function(){this.J.cB(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.p5||void 0)&&this.J.logClick(this.element)};
kV.prototype.onClick=function(E){g.fw(E,this.J,this.D,this.suggestion.sessionData||void 0)&&this.select()};
kV.prototype.onKeyPress=function(E){switch(E.keyCode){case 13:case 32:E.defaultPrevented||(this.select(),E.preventDefault())}};g.N(X$,g.O);g.I=X$.prototype;g.I.zO=function(E){this.suggestion!==E&&(this.suggestion=E,K2(this.D,E),this.playButton.updateValue("url",this.suggestion.SI()),f2(this))};
g.I.fV=function(){return this.j>0};
g.I.cN=function(){this.fV()||(this.j=Date.now(),$19(this),TGT(this.J,FcR(this)),g.VH(this.J.getRootNode(),"countdown-running",this.fV()))};
g.I.Q7=function(){this.yG();$19(this);var E=this.D.Wx("ytp-autonav-endscreen-upnext-header");E&&g.fa(E,"Up next")};
g.I.yG=function(){this.fV()&&(this.V.stop(),this.j=0)};
g.I.select=function(E){this.J.nextVideo(!1,E===void 0?!1:E);this.yG()};
g.I.U3=function(E){g.fw(E,this.J)&&(E.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):E.currentTarget===this.D.Wx("ytp-autonav-endscreen-link-container")&&(E=this.D.Wx("ytp-autonav-endscreen-link-container"),this.J.logVisibility(E,!0),this.J.logClick(E)),this.G?(this.J.w2("innertubeCommand",this.G),this.yG()):this.select())};
g.I.lY=function(){this.J.logClick(this.cancelButton.element);g.Mv(this.J,!0);this.cancelCommand&&this.J.w2("innertubeCommand",this.cancelCommand)};
g.I.onVideoDataChange=function(E,b){qe8(this,b);E=b.getWatchNextResponse();var Z,A;E=(Z=MT7(E))==null?void 0:(A=Z.cancelButton)==null?void 0:A.buttonRenderer;this.cancelCommand=E==null?void 0:E.command};
g.I.BwO=function(E){if(U18(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,Z=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(Z&&b){var A=this.element;A.style.setProperty("--w2w-start-background-color",g.RK(Z.surgeColor));A.style.setProperty("--w2w-start-primary-text-color",g.RK(Z.primaryTitleColor));A.style.setProperty("--w2w-start-secondary-text-color",g.RK(Z.secondaryTitleColor));A.style.setProperty("--w2w-end-background-color",g.RK(b.surgeColor));
A.style.setProperty("--w2w-end-primary-text-color",g.RK(b.primaryTitleColor));A.style.setProperty("--w2w-end-secondary-text-color",g.RK(b.secondaryTitleColor));A.style.setProperty("--w2w-animation-duration",E+"ms")}g.VH(this.element,"ytp-w2w-animate",!0)}};
g.I.T4=function(E){this.J.Z("web_autonav_color_transition")&&E!==2&&g.VH(this.element,"ytp-w2w-animate",!1)};
g.I.NN=function(){var E=this.J.bO();this.N&&this.nm!==E&&this.aX(E);f2(this);this.J.logVisibility(this.container.element,E);this.J.logVisibility(this.cancelButton.element,E);this.J.logVisibility(this.D.Wx("ytp-autonav-endscreen-link-container"),E);this.J.logVisibility(this.playButton.element,E)};
g.I.dV=function(E){return E.width<400||E.height<459};g.N(Q3,g.O);g.I=Q3.prototype;g.I.create=function(){this.created=!0};
g.I.destroy=function(){this.created=!1};
g.I.OP=function(){return!1};
g.I.bO=function(){return!1};
g.I.bT=function(){return!1};g.N(lT,g.O);g.I=lT.prototype;g.I.LF=function(){this.notification&&(this.V.stop(),this.Wy(this.j),this.j=null,this.notification.close(),this.notification=null)};
g.I.zO=function(E){this.suggestion=E;K2(this,E,"hqdefault.jpg")};
g.I.BF=function(){this.aX(this.api.bO());this.api.logVisibility(this.element,this.api.bO());this.api.logVisibility(this.Wx("ytp-upnext-autoplay-icon"),this.api.bO());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.bO())};
g.I.rK2=function(){window.focus();this.LF()};
g.I.cN=function(E){var b=this;this.fV()||(g.ft("a11y-announce","Up Next "+this.suggestion.title),this.T=(0,g.v)(),this.D=new g.S6(function(){sGB(b,E)},25),sGB(this,E),TGT(this.api,g5T(this,E)));
g.QH(this.element,"ytp-upnext-autoplay-paused")};
g.I.hide=function(){g.O.prototype.hide.call(this)};
g.I.fV=function(){return!!this.D};
g.I.Q7=function(){this.yG();this.T=(0,g.v)();sGB(this);g.XV(this.element,"ytp-upnext-autoplay-paused")};
g.I.yG=function(){this.fV()&&(this.D.dispose(),this.D=null)};
g.I.select=function(E){E=E===void 0?!1:E;if(this.api.C().Z("autonav_notifications")&&E&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.LF(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Ox()}),this.j=this.B(this.notification,"click",this.rK2),this.V.start())}this.yG();this.api.nextVideo(!1,E)};
g.I.kV=function(E){!g.XB(this.cancelButton.element,E.target)&&g.fw(E,this.api)&&(this.api.bO()&&this.api.logClick(this.Wx("ytp-upnext-autoplay-icon")),this.select())};
g.I.z4=function(){this.api.bO()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Mv(this.api,!0)};
g.I.iw_=function(E){this.api.getPresentingPlayerType();this.show();this.cN(E)};
g.I.JK9=function(){this.api.getPresentingPlayerType();this.yG();this.hide()};
g.I.V9=function(){this.yG();this.LF();g.O.prototype.V9.call(this)};g.N(V3,Q3);g.I=V3.prototype;g.I.create=function(){Q3.prototype.create.call(this);this.V.B(this.player,"appresize",this.ly);this.V.B(this.player,"onVideoAreaChange",this.ly);this.V.B(this.player,"videodatachange",this.onVideoDataChange);this.V.B(this.player,"autonavchange",this.fv);this.V.B(this.player,"onAutonavCancelled",this.jJ);this.onVideoDataChange()};
g.I.show=function(){Q3.prototype.show.call(this);(this.N||this.j&&this.j!==this.videoData.clientPlaybackNonce)&&g.Mv(this.player,!1);g.sd(this.player)&&this.OP()&&!this.j?(w2(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.D.select(!0):this.D.cN():this.videoData.autonavState===3&&this.D.Q7()):(g.Mv(this.player,!0),w2(this));this.ly()};
g.I.hide=function(){Q3.prototype.hide.call(this);this.D.Q7();w2(this)};
g.I.ly=function(){var E=this.player.us(!0,this.player.isFullscreen());w2(this);f2(this.T);g.VH(this.element,"ytp-autonav-cancelled-small-mode",this.dV(E));g.VH(this.element,"ytp-autonav-cancelled-tiny-mode",this.Hq(E));g.VH(this.element,"ytp-autonav-cancelled-mini-mode",E.width<=400||E.height<=360);this.overlay&&g.Y6(this.overlay.element,{width:E.width+"px"});if(!this.G)for(E=0;E<this.videos.length;E++)g.VH(this.videos[E].element,"ytp-suggestion-card-with-margin",E%2===1)};
g.I.onVideoDataChange=function(){var E=this.player.getVideoData();if(this.videoData!==E&&E){this.videoData=E;if((E=this.videoData.suggestions)&&E.length||this.player.Z("web_player_autonav_empty_suggestions_fix")){var b=g.bk(this.videoData);b&&(this.D.zO(b),this.D!==this.T&&this.T.zO(b))}if(E&&E.length)for(b=0;b<n5Z.length;++b){var Z=n5Z[b];if(E&&E[Z]){this.videos[b]=new kV(this.player);var A=this.videos[b];Z=E[Z];A.suggestion!==Z&&(A.suggestion=Z,K2(A,Z));g.R(this,this.videos[b]);this.videos[b].bD(this.S.element)}}this.ly()}};
g.I.fv=function(E){E===1?(this.N=!1,this.j=this.videoData.clientPlaybackNonce,this.D.yG(),this.nm&&this.ly()):(this.N=!0,this.bO()&&(E===2?this.D.cN():E===3&&this.D.Q7()))};
g.I.jJ=function(E){E?this.fv(1):(this.j=null,this.N=!1)};
g.I.OP=function(){return this.videoData.autonavState!==1};
g.I.dV=function(E){return(E.width<910||E.height<459)&&!this.Hq(E)&&!(E.width<=400||E.height<=360)};
g.I.Hq=function(E){return E.width<800&&!(E.width<=400||E.height<=360)};
g.I.bO=function(){return this.nm&&g.sd(this.player)&&this.OP()&&!this.j};
var n5Z=[1,3,2,4];g.N(p2,g.O);g.I=p2.prototype;g.I.Lo=function(){switch(this.buttonType){case 1:var E="Watch again on YouTube";var b=156915;break;case 2:E="Continue watching on YouTube";b=156942;break;default:E="Continue watching on YouTube",b=156942}this.update({content:E});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.I.onClick=function(E){this.J.Z("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.Qe(this.getVideoUrl(),this.J,E);this.J.Z("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.I.getVideoUrl=function(){var E=!0;switch(this.buttonType){case 1:E=!0;break;case 2:E=!1}E=this.J.getVideoUrl(E,!1,!1,!0);var b=this.J.C();if(g.qE(b)){var Z={};g.qE(b)&&g.pr(this.J,"addEmbedsConversionTrackingParams",[Z]);E=g.U5(E,Z)}return E};
g.I.logVisibility=function(){this.J.logVisibility(this.element,this.nm&&this.K)};
g.I.show=function(){g.O.prototype.show.call(this);this.logVisibility()};
g.I.hide=function(){g.O.prototype.hide.call(this);this.logVisibility()};
g.I.f7=function(E){g.O.prototype.f7.call(this,E);this.logVisibility()};g.N(Wa,Q3);Wa.prototype.show=function(){this.player.getPlayerState()!==3&&(Q3.prototype.show.call(this),this.D.Ic(!0),this.D.gG(!0),this.J.C().pW||this.D.q7(!0),this.J.logVisibility(this.element,!0),this.watchButton.f7(!0))};
Wa.prototype.hide=function(){Q3.prototype.hide.call(this);this.D.Ic(!1);this.D.gG(!1);this.D.q7(!1);this.J.logVisibility(this.element,!1);this.watchButton.f7(!1)};g.N(L2,g.O);L2.prototype.select=function(){this.api.cB(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.p5||void 0)&&this.api.logClick(this.element)};
L2.prototype.onClick=function(E){if(g.qE(this.api.C())&&this.api.Z("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.SI(),Z={};g.zE(this.api,Z);b=g.U5(b,Z);g.Qe(b,this.api,E)}else g.fw(E,this.api,this.T,this.suggestion.sessionData||void 0)&&this.select()};
L2.prototype.onKeyPress=function(E){switch(E.keyCode){case 13:case 32:E.defaultPrevented||(this.select(),E.preventDefault())}};
L2.prototype.onVideoDataChange=function(){var E=this.api.getVideoData(),b=this.api.C();this.T=E.Y_?!1:b.V};g.N(d1F,Q3);g.I=d1F.prototype;g.I.create=function(){Q3.prototype.create.call(this);var E=this.player.getVideoData();E&&(this.videoData=E);this.Uw();this.T.B(this.player,"appresize",this.Uw);this.T.B(this.player,"onVideoAreaChange",this.Uw);this.T.B(this.player,"videodatachange",this.onVideoDataChange);this.T.B(this.player,"autonavchange",this.bk);this.T.B(this.player,"onAutonavCancelled",this.V3);E=this.videoData.autonavState;E!==this.S&&this.bk(E);this.T.B(this.element,"transitionend",this.On)};
g.I.destroy=function(){g.qC(this.T);g.Ll(this.stills);this.stills=[];Q3.prototype.destroy.call(this);g.QH(this.element,"ytp-show-tiles");this.G.stop();this.S=this.videoData.autonavState};
g.I.OP=function(){return this.videoData.autonavState!==1};
g.I.show=function(){var E=this.nm;Q3.prototype.show.call(this);g.QH(this.element,"ytp-show-tiles");this.player.C().T?g.c8(this.G):this.G.start();(this.V||this.j&&this.j!==this.videoData.clientPlaybackNonce)&&g.Mv(this.player,!1);Ba(this)?(iT(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.D.select(!0):this.D.cN():this.videoData.autonavState===3&&this.D.Q7()):(g.Mv(this.player,!0),iT(this));E!==this.nm&&this.player.logVisibility(this.element,!0)};
g.I.hide=function(){var E=this.nm;Q3.prototype.hide.call(this);this.D.Q7();iT(this);E!==this.nm&&this.player.logVisibility(this.element,!1)};
g.I.On=function(E){E.target===this.element&&this.Uw()};
g.I.Uw=function(){var E,b,Z,A;var K=((E=this.videoData)==null?0:(b=E.suggestions)==null?0:b.length)?(Z=this.videoData)==null?void 0:Z.suggestions:[(A=this.videoData)==null?void 0:g.bk(A)];if(K.length){b=this.J.us(!0,this.J.isFullscreen());E=Math.floor((b.width-64+16)/(g.M4(b.width*.27,250,450)+16));b=Math.min(3,Math.floor((b.height-64)/((b.width-64-(E-1)*16)/E*.5625+70)));g.lZ(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.XV(this.element,"ytp-modern-endscreen-limit-rows-"+b);g.VH(this.element,"ytp-modern-endscreen-single-item",E===1);g.VH(this.element,"ytp-modern-endscreen-row-0",b===0);E=this.table.element;E.ariaLive="polite";this.D.zO(g.bk(this.videoData));this.D instanceof X$&&f2(this.D);g.VH(this.element,"ytp-endscreen-takeover",Ba(this));iT(this);b=0;E.ariaBusy="true";Z=K.length;for(A=0;A<Z;A++){var k=A%Z,X=this.stills[A];X||(X=new L2(this.player),this.stills[A]=X,E.appendChild(X.element));k=K[k];if(X.suggestion!==
k){X.suggestion=k;var Q=X.api.C();K2(X,k,"hqdefault.jpg");if(g.qE(Q)&&!X.api.Z("web_player_log_click_before_generating_ve_conversion_params")){Q=k.SI();var l={};g.pr(X.api,"addEmbedsConversionTrackingParams",[l]);Q=g.U5(Q,l);X.updateValue("url",Q)}(k=(k=k.sessionData)&&k.itct)&&X.api.setTrackingParams(X.element,k)}b++}this.stills.length=b}};
g.I.onVideoDataChange=function(){var E=this.player.getVideoData(1);this.videoData!==E&&(E!=null&&g.bk(E)?(this.videoData=E,this.Uw()):this.player.Tv("missg",{vid:(E==null?void 0:E.videoId)||"",cpn:(E==null?void 0:E.clientPlaybackNonce)||""}))};
g.I.bT=function(){return this.D.fV()};
g.I.bk=function(E){E===1?(this.V=!1,this.j=this.videoData.clientPlaybackNonce,this.D.yG(),this.nm&&this.Uw()):(this.V=!0,this.nm&&Ba(this)&&(E===2?this.D.cN():E===3&&this.D.Q7()))};
g.I.V3=function(E){if(E){for(E=0;E<this.stills.length;E++)this.J.logVisibility(this.stills[E].element,!0);this.bk(1)}else this.j=null,this.V=!1;this.Uw()};
g.I.bO=function(){return this.nm&&Ba(this)};g.N(YeB,Q3);YeB.prototype.uD=function(){var E=this.player.getVideoData();this.D.update({profilePicture:E.profilePicture,author:E.author});this.subscribeButton.channelId=E.TU;var b=this.subscribeButton;E.subscribed?b.D():b.T()};g.N(Ix,g.O);Ix.prototype.select=function(){this.api.cB(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.p5||void 0)&&this.api.logClick(this.element)};
Ix.prototype.onClick=function(E){if(g.qE(this.api.C())&&this.api.Z("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.SI(),Z={};g.zE(this.api,Z);b=g.U5(b,Z);g.Qe(b,this.api,E)}else g.fw(E,this.api,this.T,this.suggestion.sessionData||void 0)&&this.select()};
Ix.prototype.onKeyPress=function(E){switch(E.keyCode){case 13:case 32:E.defaultPrevented||(this.select(),E.preventDefault())}};
Ix.prototype.onVideoDataChange=function(){var E=this.api.getVideoData(),b=this.api.C();this.T=E.Y_?!1:b.V};g.N(Nt,Q3);g.I=Nt.prototype;g.I.create=function(){Q3.prototype.create.call(this);var E=this.player.getVideoData();E&&(this.videoData=E);this.HJ();this.T.B(this.player,"appresize",this.HJ);this.T.B(this.player,"onVideoAreaChange",this.HJ);this.T.B(this.player,"videodatachange",this.onVideoDataChange);this.T.B(this.player,"autonavchange",this.G$);this.T.B(this.player,"onAutonavCancelled",this.xV);E=this.videoData.autonavState;E!==this.L&&this.G$(E);this.T.B(this.element,"transitionend",this.Jm)};
g.I.destroy=function(){g.qC(this.T);g.Ll(this.stills);this.stills=[];Q3.prototype.destroy.call(this);g.QH(this.element,"ytp-show-tiles");this.N.stop();this.L=this.videoData.autonavState};
g.I.OP=function(){return this.videoData.autonavState!==1};
g.I.show=function(){var E=this.nm;Q3.prototype.show.call(this);g.QH(this.element,"ytp-show-tiles");this.player.C().T?g.c8(this.N):this.N.start();(this.G||this.V&&this.V!==this.videoData.clientPlaybackNonce)&&g.Mv(this.player,!1);J4(this)?(r2(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.D.select(!0):this.D.cN():this.videoData.autonavState===3&&this.D.Q7()):(g.Mv(this.player,!0),r2(this));E!==this.nm&&this.player.logVisibility(this.element,!0)};
g.I.hide=function(){var E=this.nm;Q3.prototype.hide.call(this);this.D.Q7();r2(this);E!==this.nm&&this.player.logVisibility(this.element,!1)};
g.I.Jm=function(E){E.target===this.element&&this.HJ()};
g.I.HJ=function(){var E,b,Z,A;var K=((E=this.videoData)==null?0:(b=E.suggestions)==null?0:b.length)?(Z=this.videoData)==null?void 0:Z.suggestions:[(A=this.videoData)==null?void 0:g.bk(A)];if(K.length){g.XV(this.element,"ytp-endscreen-paginate");var k=this.J.us(!0,this.J.isFullscreen());if(E=g.Ik(this.J))E=E.Wo()?48:32,k.width-=E*2;var X=k.width/k.height;A=96/54;b=E=2;var Q=Math.max(k.width/96,2),l=Math.max(k.height/54,2);Z=K.length;var V=Z*4;for(V-=4;V>0&&(E<Q||b<l);){var w=E/2,p=b/2,W=E<=Q-2&&V>=
p*4,L=b<=l-2&&V>=w*4;if((w+1)/p*A/X>X/(w/(p+1)*A)&&L)V-=w*4,b+=2;else if(W)V-=p*4,E+=2;else if(L)V-=w*4,b+=2;else break}A=!1;V>=12&&Z*4-V<=6&&(b>=4||E>=4)&&(A=!0);V=E*96;Q=b*54;X=V/Q<X?k.height/Q:k.width/V;X=Math.min(X,2);V=Math.floor(Math.min(k.width,V*X));Q=Math.floor(Math.min(k.height,Q*X));k=this.table.element;k.ariaLive="polite";g.uK(k,V,Q);g.Y6(k,{marginLeft:V/-2+"px",marginTop:Q/-2+"px"});this.D.zO(g.bk(this.videoData));this.D instanceof X$&&f2(this.D);g.VH(this.element,"ytp-endscreen-takeover",
J4(this));r2(this);V+=4;Q+=4;X=0;k.ariaBusy="true";for(l=0;l<E;l++)for(w=0;w<b;w++)if(p=X,L=0,A&&l>=E-2&&w>=b-2?L=1:w%2===0&&l%2===0&&(w<2&&l<2?w===0&&l===0&&(L=2):L=2),p=g.q4(p+this.j,Z),L!==0){W=this.stills[X];W||(W=new Ix(this.player),this.stills[X]=W,k.appendChild(W.element));var B=Math.floor(Q*w/b),r=Math.floor(V*l/E),a=Math.floor(Q*(w+L)/b)-B-4,x=Math.floor(V*(l+L)/E)-r-4;g.vW(W.element,r,B);g.uK(W.element,x,a);g.Y6(W.element,"transitionDelay",(w+l)/20+"s");g.VH(W.element,"ytp-videowall-still-mini",
L===1);g.VH(W.element,"ytp-videowall-still-large",L>2);L=Math.max(x,a);g.VH(W.element,"ytp-videowall-still-round-large",L>=256);g.VH(W.element,"ytp-videowall-still-round-medium",L>96&&L<256);g.VH(W.element,"ytp-videowall-still-round-small",L<=96);p=K[p];W.suggestion!==p&&(W.suggestion=p,L=W.api.C(),B=g.k9(W.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",K2(W,p,B),g.qE(L)&&!W.api.Z("web_player_log_click_before_generating_ve_conversion_params")&&(L=p.SI(),B={},g.pr(W.api,"addEmbedsConversionTrackingParams",
[B]),L=g.U5(L,B),W.updateValue("url",L)),(p=(p=p.sessionData)&&p.itct)&&W.api.setTrackingParams(W.element,p));X++}k.ariaBusy="false";g.VH(this.element,"ytp-endscreen-paginate",X<Z);for(K=this.stills.length-1;K>=X;K--)E=this.stills[K],g.kX(E.element),g.WH(E);this.stills.length=X}};
g.I.onVideoDataChange=function(){var E=this.player.getVideoData(1);this.videoData!==E&&(E!=null&&g.bk(E)?(this.j=0,this.videoData=E,this.HJ()):this.player.Tv("missg",{vid:(E==null?void 0:E.videoId)||"",cpn:(E==null?void 0:E.clientPlaybackNonce)||""}))};
g.I.Wk=function(){this.j+=this.stills.length;this.HJ()};
g.I.iY=function(){this.j-=this.stills.length;this.HJ()};
g.I.bT=function(){return this.D.fV()};
g.I.G$=function(E){E===1?(this.G=!1,this.V=this.videoData.clientPlaybackNonce,this.D.yG(),this.nm&&this.HJ()):(this.G=!0,this.nm&&J4(this)&&(E===2?this.D.cN():E===3&&this.D.Q7()))};
g.I.xV=function(E){if(E){for(E=0;E<this.stills.length;E++)this.J.logVisibility(this.stills[E].element,!0);this.G$(1)}else this.V=null,this.G=!1;this.HJ()};
g.I.bO=function(){return this.nm&&J4(this)};g.N(ax,Q3);ax.prototype.hasSuggestions=function(){var E;return(E=this.D)==null?void 0:E.hasSuggestions()};
ax.prototype.show=function(){if(this.player.getPlayerState()!==3){Q3.prototype.show.call(this);var E=this.T;if(E){var b=this.D.hasSuggestions();g.VH(this.element,"ytp-shorts-branded-ui",b);b?E.show():E.hide()}var Z;(Z=g.Ik(this.player))==null||Z.TD(!0);this.player.logVisibility(this.element,!0);this.watchButton.f7(!0)}};
ax.prototype.hide=function(){Q3.prototype.hide.call(this);var E;(E=g.Ik(this.player))==null||E.TD(!1);this.player.logVisibility(this.element,!1);this.watchButton.f7(!1)};g.N(ylB,g.BM);g.I=ylB.prototype;g.I.Tx=function(){var E=this.player.getVideoData(),b=E.mutedAutoplay&&(E.limitedPlaybackDurationInSeconds>0||E.endSeconds>0||E.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.T)&&!b)return!0;var Z;var A=!!((E==null?0:g.bk(E))||(E==null?0:(Z=E.suggestions)==null?0:Z.length));A=!C97(this.player)||A;E=E.Mh;Z=this.player.MR();return A&&!E&&!Z&&!b};
g.I.bO=function(){return this.endScreen.bO()};
g.I.bmq=function(){return this.bO()?this.endScreen.bT():!1};
g.I.V9=function(){this.player.r6("endscreen");g.BM.prototype.V9.call(this)};
g.I.load=function(){var E=this.player.getVideoData();var b=E.transitionEndpointAtEndOfStream;if(b&&b.videoId){var Z=this.player.jy().d6.get("heartbeat"),A=g.bk(E);!A||b.videoId!==A.videoId||E.ZN?(this.player.cB(b.videoId,void 0,void 0,!0,!0,b),Z&&Z.d9("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),E=!0):E=!1}else E=!1;E||(g.BM.prototype.load.call(this),this.endScreen.show())};
g.I.unload=function(){g.BM.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.I.onCueRangeEnter=function(E){this.Tx()&&(this.endScreen.created||this.endScreen.create(),E.getId()==="load"&&this.load())};
g.I.onCueRangeExit=function(E){E.getId()==="load"&&this.loaded&&this.unload()};
g.I.onVideoDataChange=function(){o5s(this);this.V&&Rzs(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.D?this.endScreen=new V3(this.player):this.endScreen=new Nt(this.player),g.R(this,this.endScreen),g.gP(this.player,this.endScreen.element,4))};g.LK("endscreen",ylB);})(_yt_player);
